import { createHash } from 'node:crypto';
import { copyFile, mkdir, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import type { ProjectFeature } from '../../src/types.ts';

const UA = 'atxwip/0.1 (+https://github.com/mracette/atxwip)';
const WIDTH = 960;
/** Anything narrower is a thumbnail or an icon, not something worth a panel hero. */
const MIN_WIDTH = 480;

export interface ImageReport {
  failed: { id: string; name: string; url: string; reason: string }[];
  missing: { id: string; name: string; why: string }[];
}

/**
 * Replaces each project's remote `image` URL with a resized local copy. Copies
 * are kept in `cacheDir` between runs, so an image that later disappears
 * upstream keeps showing; only never-downloaded images can fail.
 */
export async function localizeImages(features: ProjectFeature[], cacheDir: string, outDir: string): Promise<ImageReport> {
  await mkdir(cacheDir, { recursive: true });
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });
  const report: ImageReport = { failed: [], missing: [] };
  const used = new Set<string>();
  const byUrl = new Map<string, Promise<string>>();

  for (const f of features) {
    const url = f.properties.image;
    if (!url || !/^https?:/.test(url)) continue;
    const file = `${createHash('sha1').update(url).digest('hex').slice(0, 16)}.webp`;
    if (!byUrl.has(url)) byUrl.set(url, ensureCached(url, path.join(cacheDir, file)).then(() => file));
    try {
      await byUrl.get(url);
      used.add(file);
      f.properties.image = `data/images/${file}`;
    } catch (err) {
      report.failed.push({ id: f.properties.id, name: f.properties.name, url, reason: (err as Error).message });
      delete f.properties.image;
      delete f.properties.imageCredit;
    }
  }

  for (const file of used) await copyFile(path.join(cacheDir, file), path.join(outDir, file));
  // Unused copies are dropped so the cache tracks what the map shows.
  for (const file of await readdir(cacheDir)) if (!used.has(file)) await rm(path.join(cacheDir, file));
  return report;
}

async function ensureCached(url: string, dest: string): Promise<void> {
  if (await stat(dest).then(() => true, () => false)) return;
  let res = await get(url);
  // Some sources link the photo's web page rather than the file; follow its preview image.
  if (res.headers.get('content-type')?.includes('text/html')) {
    const og = (await res.text()).match(/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i)?.[1];
    if (!og) throw new Error('page has no preview image');
    res = await get(new URL(og, url).href);
  }
  const img = sharp(Buffer.from(await res.arrayBuffer()));
  const { width = 0 } = await img.metadata();
  if (width < MIN_WIDTH) throw new Error(`only ${width}px wide`);
  await img.rotate().resize({ width: WIDTH, withoutEnlargement: true }).webp({ quality: 72 }).toFile(dest);
}

async function get(url: string): Promise<Response> {
  const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'image/*,text/html;q=0.5' }, signal: AbortSignal.timeout(60_000), redirect: 'follow' });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  return res;
}

/** Big, visible projects that still have no picture: the list worth a few minutes of hand-picking. */
export function missingImages(features: ProjectFeature[]): ImageReport['missing'] {
  return features
    .filter((f) => !f.properties.image && !f.properties.small && f.properties.status !== 'complete')
    .map((f) => {
      const p = f.properties;
      const why = (p.floors ?? 0) >= 10 ? `${p.floors} floors` : (p.cost ?? 0) >= 100_000_000 ? `$${Math.round(p.cost! / 1e6)}M` : '';
      return { id: p.id, name: p.name, why };
    })
    .filter((m) => m.why);
}

export async function writeImageReport(report: ImageReport, file: string): Promise<void> {
  const handPicked = report.failed.filter((f) => !f.id.startsWith('cpe-'));
  const cityDead = report.failed.length - handPicked.length;
  const lines = [
    'Generated by the daily data build. Add an image by giving the project `image` and `imageCredit` in `scripts/curated.ts`.',
    '',
    `## Hand-picked images that failed to download (${handPicked.length})`,
    ...(handPicked.length ? handPicked.map((f) => `- \`${f.id}\` ${f.name}: ${f.reason} (${f.url})`) : ['None.']),
    '',
    `${cityDead} City of Austin photos are dead links on the city's side; those projects show their footprint drawing instead.`,
    '',
    `## Big projects with no image (${report.missing.length})`,
    ...(report.missing.length ? report.missing.map((m) => `- \`${m.id}\` ${m.name} (${m.why})`) : ['None.']),
    '',
  ];
  await writeFile(file, lines.join('\n'));
}
